name: extended_image
description: Official extension image, support placeholder for loading/failed state, cache network, zoom/pan, photo view, slide out page, editor (crop, rotate, flip), painting etc.
version: 10.1.0
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues
topics:
  - image
  - cropper
  - photo-view
  - editor
  - slide-out

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image_library: ^5.0.0

  meta: ^1.7.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: any
