// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_40_png.preview}
  static const String assets_40_png = 'assets/40.png';

  /// {@macro assets_generator.assets_avatar_jpg.preview}
  static const String assets_avatar_jpg = 'assets/avatar.jpg';

  /// {@macro assets_generator.assets_c8abd91c6f1a5dbf4e4cc6811b0173d8_jpg.preview}
  static const String assets_c8abd91c6f1a5dbf4e4cc6811b0173d8_jpg =
      'assets/c8abd91c6f1a5dbf4e4cc6811b0173d8.JPG';

  static const String assets_c8abd91c6f1a5dbf4e4cc6811b0173d8_mov =
      'assets/c8abd91c6f1a5dbf4e4cc6811b0173d8.mov';

  /// {@macro assets_generator.assets_failed_jpg.preview}
  static const String assets_failed_jpg = 'assets/failed.jpg';

  /// {@macro assets_generator.assets_fluttercandies_grey_png.preview}
  static const String assets_fluttercandies_grey_png =
      'assets/flutterCandies_grey.png';

  /// {@macro assets_generator.assets_image_jpg.preview}
  static const String assets_image_jpg = 'assets/image.jpg';

  /// {@macro assets_generator.assets_loading_gif.preview}
  static const String assets_loading_gif = 'assets/loading.gif';

  /// {@macro assets_generator.assets_love_png.preview}
  static const String assets_love_png = 'assets/love.png';

  /// {@macro assets_generator.assets_sun_glasses_png.preview}
  static const String assets_sun_glasses_png = 'assets/sun_glasses.png';
}
