// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import,library_private_types_in_public_api
import 'package:example/common/data/tu_chong_source.dart' hide asT;
import 'package:example/common/model/pic_swiper_item.dart';
import 'package:flutter/foundation.dart';

import 'pages/main_page.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://LivePhotoDemo',
  'fluttercandies://LivePhotoPicsWiper',
  'fluttercandies://MemoryUsageDemo',
  'fluttercandies://SimplePhotoView',
  'fluttercandies://SimplePicsWiper',
  'fluttercandies://WaterfallFlowDemo',
  'fluttercandies://customimage',
  'fluttercandies://demogrouppage',
  'fluttercandies://extendedImageGesturePageView',
  'fluttercandies://image',
  'fluttercandies://imageeditor',
  'fluttercandies://loadingprogress',
  'fluttercandies://mainpage',
  'fluttercandies://paintimage',
  'fluttercandies://photoview',
  'fluttercandies://picswiper',
  'fluttercandies://simpleimageeditor',
  'fluttercandies://slidepage',
  'fluttercandies://slidepageitem',
  'fluttercandies://zoomimage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'a live photho demo.'
  ///
  /// [name] : 'fluttercandies://LivePhotoDemo'
  ///
  /// [routeName] : 'LivePhoto'
  ///
  /// [description] : 'a live photho demo.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 5}
  static const String fluttercandiesLivePhotoDemo =
      'fluttercandies://LivePhotoDemo';

  /// 'demo for LivePhoto Pics Wiper.'
  ///
  /// [name] : 'fluttercandies://LivePhotoPicsWiper'
  ///
  /// [routeName] : 'LivePhotoPicsWiper'
  ///
  /// [description] : 'demo for LivePhoto Pics Wiper.'
  ///
  /// [constructors] :
  ///
  /// LivePhotoPicsWiper : [String(required) url, List<String>(required) images, bool stopPlayLivePhotoWhenSlidingPage, bool stopPlayLivePhotoWhenGesture]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesLivePhotoPicsWiper
      fluttercandiesLivePhotoPicsWiper = _FluttercandiesLivePhotoPicsWiper();

  /// 'show how to reduce memory usage.'
  ///
  /// [name] : 'fluttercandies://MemoryUsageDemo'
  ///
  /// [routeName] : 'MemoryUsage'
  ///
  /// [description] : 'show how to reduce memory usage.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 3}
  static const String fluttercandiesMemoryUsageDemo =
      'fluttercandies://MemoryUsageDemo';

  /// 'Simple demo for PhotoView.'
  ///
  /// [name] : 'fluttercandies://SimplePhotoView'
  ///
  /// [routeName] : 'SimplePhotoView'
  ///
  /// [description] : 'Simple demo for PhotoView.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 8}
  static const String fluttercandiesSimplePhotoView =
      'fluttercandies://SimplePhotoView';

  /// 'Simple demo for Simple Pics Wiper.'
  ///
  /// [name] : 'fluttercandies://SimplePicsWiper'
  ///
  /// [routeName] : 'SimplePicsWiper'
  ///
  /// [description] : 'Simple demo for Simple Pics Wiper.'
  ///
  /// [constructors] :
  ///
  /// SimplePicsWiper : [String(required) url, List<String>(required) images]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesSimplePicsWiper fluttercandiesSimplePicsWiper =
      _FluttercandiesSimplePicsWiper();

  /// 'WaterfallFlow with ExtendedImage.'
  ///
  /// [name] : 'fluttercandies://WaterfallFlowDemo'
  ///
  /// [routeName] : 'WaterfallFlow'
  ///
  /// [description] : 'WaterfallFlow with ExtendedImage.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 0}
  static const String fluttercandiesWaterfallFlowDemo =
      'fluttercandies://WaterfallFlowDemo';

  /// 'Custom state for loading, failed and completed.'
  ///
  /// [name] : 'fluttercandies://customimage'
  ///
  /// [routeName] : 'Custom load state'
  ///
  /// [description] : 'Custom state for loading, failed and completed.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const String fluttercandiesCustomimage =
      'fluttercandies://customimage';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const _FluttercandiesDemogrouppage fluttercandiesDemogrouppage =
      _FluttercandiesDemogrouppage();

  /// 'Simple demo for ExtendedImageGesturePageView.'
  ///
  /// [name] : 'fluttercandies://extendedImageGesturePageView'
  ///
  /// [routeName] : 'ExtendedImageGesturePageView'
  ///
  /// [description] : 'Simple demo for ExtendedImageGesturePageView.'
  ///
  /// [showStatusBar] : false
  ///
  /// [exts] : {'group': 'Simple', 'order': 7}
  static const String fluttercandiesExtendedImageGesturePageView =
      'fluttercandies://extendedImageGesturePageView';

  /// 'Cached image with border,shape,borderRadius.'
  ///
  /// [name] : 'fluttercandies://image'
  ///
  /// [routeName] : 'Image'
  ///
  /// [description] : 'Cached image with border,shape,borderRadius.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const String fluttercandiesImage = 'fluttercandies://image';

  /// 'Crop,rotate and flip with image editor.'
  ///
  /// [name] : 'fluttercandies://imageeditor'
  ///
  /// [routeName] : 'ImageEditor'
  ///
  /// [description] : 'Crop,rotate and flip with image editor.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 1}
  static const String fluttercandiesImageeditor =
      'fluttercandies://imageeditor';

  /// 'Loading progress for network image.'
  ///
  /// [name] : 'fluttercandies://loadingprogress'
  ///
  /// [routeName] : 'Loading progress'
  ///
  /// [description] : 'Loading progress for network image.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const String fluttercandiesLoadingprogress =
      'fluttercandies://loadingprogress';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'Paint any thing before or after raw image is painted.'
  ///
  /// [name] : 'fluttercandies://paintimage'
  ///
  /// [routeName] : 'Paint image'
  ///
  /// [description] : 'Paint any thing before or after raw image is painted.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 3}
  static const String fluttercandiesPaintimage = 'fluttercandies://paintimage';

  /// 'Complex demo for photo view.'
  ///
  /// [name] : 'fluttercandies://photoview'
  ///
  /// [routeName] : 'PhotoView'
  ///
  /// [description] : 'Complex demo for photo view.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 2}
  static const String fluttercandiesPhotoview = 'fluttercandies://photoview';

  /// 'PicSwiper'
  ///
  /// [name] : 'fluttercandies://picswiper'
  ///
  /// [routeName] : 'PicSwiper'
  ///
  /// [constructors] :
  ///
  /// PicSwiper : [int? index, List<PicSwiperItem>? pics, TuChongItem? tuChongItem]
  ///
  /// [showStatusBar] : false
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesPicswiper fluttercandiesPicswiper =
      _FluttercandiesPicswiper();

  /// 'Crop with image editor.'
  ///
  /// [name] : 'fluttercandies://simpleimageeditor'
  ///
  /// [routeName] : 'ImageEditor'
  ///
  /// [description] : 'Crop with image editor.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 6}
  static const String fluttercandiesSimpleimageeditor =
      'fluttercandies://simpleimageeditor';

  /// 'Simple demo for slide page.'
  ///
  /// [name] : 'fluttercandies://slidepage'
  ///
  /// [routeName] : 'SlidePage'
  ///
  /// [description] : 'Simple demo for slide page.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 5}
  static const String fluttercandiesSlidepage = 'fluttercandies://slidepage';

  /// 'Simple demo for Sliding.'
  ///
  /// [name] : 'fluttercandies://slidepageitem'
  ///
  /// [routeName] : 'SlidePageItem'
  ///
  /// [description] : 'Simple demo for Sliding.'
  ///
  /// [constructors] :
  ///
  /// SlidePage : [String? url]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesSlidepageitem fluttercandiesSlidepageitem =
      _FluttercandiesSlidepageitem();

  /// 'Zoom and Pan.'
  ///
  /// [name] : 'fluttercandies://zoomimage'
  ///
  /// [routeName] : 'ImageZoom'
  ///
  /// [description] : 'Zoom and Pan.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 4}
  static const String fluttercandiesZoomimage = 'fluttercandies://zoomimage';
}

class _FluttercandiesLivePhotoPicsWiper {
  const _FluttercandiesLivePhotoPicsWiper();

  String get name => 'fluttercandies://LivePhotoPicsWiper';

  Map<String, dynamic> d({
    Key? key,
    required String url,
    required List<String> images,
    bool stopPlayLivePhotoWhenSlidingPage = false,
    bool stopPlayLivePhotoWhenGesture = false,
  }) =>
      <String, dynamic>{
        'key': key,
        'url': url,
        'images': images,
        'stopPlayLivePhotoWhenSlidingPage': stopPlayLivePhotoWhenSlidingPage,
        'stopPlayLivePhotoWhenGesture': stopPlayLivePhotoWhenGesture,
      };

  @override
  String toString() => name;
}

class _FluttercandiesSimplePicsWiper {
  const _FluttercandiesSimplePicsWiper();

  String get name => 'fluttercandies://SimplePicsWiper';

  Map<String, dynamic> d({
    required String url,
    required List<String> images,
  }) =>
      <String, dynamic>{
        'url': url,
        'images': images,
      };

  @override
  String toString() => name;
}

class _FluttercandiesDemogrouppage {
  const _FluttercandiesDemogrouppage();

  String get name => 'fluttercandies://demogrouppage';

  Map<String, dynamic> d({
    required MapEntry<String, List<DemoRouteResult>> keyValue,
  }) =>
      <String, dynamic>{
        'keyValue': keyValue,
      };

  @override
  String toString() => name;
}

class _FluttercandiesPicswiper {
  const _FluttercandiesPicswiper();

  String get name => 'fluttercandies://picswiper';

  Map<String, dynamic> d({
    int? index,
    List<PicSwiperItem>? pics,
    TuChongItem? tuChongItem,
  }) =>
      <String, dynamic>{
        'index': index,
        'pics': pics,
        'tuChongItem': tuChongItem,
      };

  @override
  String toString() => name;
}

class _FluttercandiesSlidepageitem {
  const _FluttercandiesSlidepageitem();

  String get name => 'fluttercandies://slidepageitem';

  Map<String, dynamic> d({
    String? url,
  }) =>
      <String, dynamic>{
        'url': url,
      };

  @override
  String toString() => name;
}
