// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://WaterfallFlowDemo',
  'fluttercandies://customimage',
  'fluttercandies://image',
  'fluttercandies://imageeditor',
  'fluttercandies://loadingprogress',
  'fluttercandies://mainpage',
  'fluttercandies://paintimage',
  'fluttercandies://photoview',
  'fluttercandies://picswiper',
  'fluttercandies://zoomimage'
];

class Routes {
  const Routes._();

  /// "show how to build loading more WaterfallFlow with ExtendedImage."
  ///
  /// [name] : fluttercandies://WaterfallFlowDemo
  ///
  /// [routeName] : WaterfallFlow
  ///
  /// [description] : "show how to build loading more WaterfallFlow with ExtendedImage."
  static const String fluttercandiesWaterfallFlowDemo =
      'fluttercandies://WaterfallFlowDemo';

  /// "show image with loading,failed,animation state"
  ///
  /// [name] : fluttercandies://customimage
  ///
  /// [routeName] : custom image load state
  ///
  /// [description] : "show image with loading,failed,animation state"
  static const String fluttercandiesCustomimage =
      'fluttercandies://customimage';

  /// "cache image,save to photo Library,image border,shape,borderRadius"
  ///
  /// [name] : fluttercandies://image
  ///
  /// [routeName] : image
  ///
  /// [description] : "cache image,save to photo Library,image border,shape,borderRadius"
  static const String fluttercandiesImage = 'fluttercandies://image';

  /// "crop,rotate and flip with image editor"
  ///
  /// [name] : fluttercandies://imageeditor
  ///
  /// [routeName] : image editor
  ///
  /// [description] : "crop,rotate and flip with image editor"
  static const String fluttercandiesImageeditor =
      'fluttercandies://imageeditor';

  /// "show how to make loading progress for network image"
  ///
  /// [name] : fluttercandies://loadingprogress
  ///
  /// [routeName] : loading progress
  ///
  /// [description] : "show how to make loading progress for network image"
  static const String fluttercandiesLoadingprogress =
      'fluttercandies://loadingprogress';

  /// MainPage
  ///
  /// [name] : fluttercandies://mainpage
  ///
  /// [routeName] : MainPage
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// "show how to paint any thing before/after image is painted"
  ///
  /// [name] : fluttercandies://paintimage
  ///
  /// [routeName] : paint image
  ///
  /// [description] : "show how to paint any thing before/after image is painted"
  static const String fluttercandiesPaintimage = 'fluttercandies://paintimage';

  /// "show how to zoom/pan image in page view like WeChat"
  ///
  /// [name] : fluttercandies://photoview
  ///
  /// [routeName] : photo view
  ///
  /// [description] : "show how to zoom/pan image in page view like WeChat"
  static const String fluttercandiesPhotoview = 'fluttercandies://photoview';

  /// PicSwiper
  ///
  /// [name] : fluttercandies://picswiper
  ///
  /// [routeName] : PicSwiper
  ///
  /// [arguments] : [index, pics, tuChongItem]
  ///
  /// [showStatusBar] : false
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String fluttercandiesPicswiper = 'fluttercandies://picswiper';

  /// "show how to zoom/pan image"
  ///
  /// [name] : fluttercandies://zoomimage
  ///
  /// [routeName] : image zoom
  ///
  /// [description] : "show how to zoom/pan image"
  static const String fluttercandiesZoomimage = 'fluttercandies://zoomimage';
}
