// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:example/common/data/tu_chong_source.dart' hide asT;
import 'package:example/common/model/pic_swiper_item.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'common/widget/pic_swiper.dart';
import 'pages/complex/image_editor_demo.dart';
import 'pages/complex/live_photo_demo.dart';
import 'pages/complex/memory_usage_demo.dart';
import 'pages/complex/photo_view_demo.dart';
import 'pages/complex/waterfall_flow_demo.dart';
import 'pages/main_page.dart';
import 'pages/simple/custom_image_demo.dart';
import 'pages/simple/image_demo.dart';
import 'pages/simple/image_editor_demo.dart';
import 'pages/simple/loading_progress.dart';
import 'pages/simple/paint_image_demo.dart';
import 'pages/simple/photo_view_demo.dart'
    as simplephotoviewdemo0085a2a34d373fe52ef79255573dc760;
import 'pages/simple/simple_photo_view_demo.dart'
    as simplephotoviewdemo8f7565503637697990b9e02e846a83f9;
import 'pages/simple/simple_photo_view_demo.dart' hide SimplePhotoViewDemo;
import 'pages/simple/slide_page_demo.dart';
import 'pages/simple/zoom_image_demo.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://LivePhotoDemo':
      return FFRouteSettings(
        name: 'fluttercandies://LivePhotoDemo',
        routeName: 'LivePhoto',
        description: 'a live photho demo.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Complex', 'order': 5},
        builder: () => LivePhotoDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://LivePhotoPicsWiper':
      return FFRouteSettings(
        name: 'fluttercandies://LivePhotoPicsWiper',
        routeName: 'LivePhotoPicsWiper',
        description: 'demo for LivePhoto Pics Wiper.',
        arguments: arguments,
        pageRouteType: PageRouteType.transparent,
        builder: () => LivePhotoPicsWiper(
          key: asT<Key?>(safeArguments['key']),
          url: asT<String>(safeArguments['url'])!,
          images: asT<List<String>>(safeArguments['images'])!,
          stopPlayLivePhotoWhenSlidingPage: asT<bool>(
            safeArguments['stopPlayLivePhotoWhenSlidingPage'],
            false,
          )!,
          stopPlayLivePhotoWhenGesture: asT<bool>(
            safeArguments['stopPlayLivePhotoWhenGesture'],
            false,
          )!,
        ),
      );
    case 'fluttercandies://MemoryUsageDemo':
      return FFRouteSettings(
        name: 'fluttercandies://MemoryUsageDemo',
        routeName: 'MemoryUsage',
        description: 'show how to reduce memory usage.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Complex', 'order': 3},
        builder: () => MemoryUsageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://SimplePhotoView':
      return FFRouteSettings(
        name: 'fluttercandies://SimplePhotoView',
        routeName: 'SimplePhotoView',
        description: 'Simple demo for PhotoView.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 8},
        builder: () => simplephotoviewdemo8f7565503637697990b9e02e846a83f9
            .SimplePhotoViewDemo(
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case 'fluttercandies://SimplePicsWiper':
      return FFRouteSettings(
        name: 'fluttercandies://SimplePicsWiper',
        routeName: 'SimplePicsWiper',
        description: 'Simple demo for Simple Pics Wiper.',
        arguments: arguments,
        pageRouteType: PageRouteType.transparent,
        builder: () => SimplePicsWiper(
          key: asT<Key?>(safeArguments['key']),
          url: asT<String>(safeArguments['url'])!,
          images: asT<List<String>>(safeArguments['images'])!,
        ),
      );
    case 'fluttercandies://WaterfallFlowDemo':
      return FFRouteSettings(
        name: 'fluttercandies://WaterfallFlowDemo',
        routeName: 'WaterfallFlow',
        description: 'WaterfallFlow with ExtendedImage.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Complex', 'order': 0},
        builder: () => WaterfallFlowDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://customimage':
      return FFRouteSettings(
        name: 'fluttercandies://customimage',
        routeName: 'Custom load state',
        description: 'Custom state for loading, failed and completed.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
        builder: () => CustomImageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: 'fluttercandies://demogrouppage',
        routeName: 'DemoGroupPage',
        arguments: arguments,
        builder: () => DemoGroupPage(
          key: asT<Key?>(safeArguments['key']),
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
            safeArguments['keyValue'],
          )!,
        ),
      );
    case 'fluttercandies://extendedImageGesturePageView':
      return FFRouteSettings(
        name: 'fluttercandies://extendedImageGesturePageView',
        routeName: 'ExtendedImageGesturePageView',
        description: 'Simple demo for ExtendedImageGesturePageView.',
        arguments: arguments,
        showStatusBar: false,
        exts: <String, dynamic>{'group': 'Simple', 'order': 7},
        builder: () => simplephotoviewdemo0085a2a34d373fe52ef79255573dc760
            .SimplePhotoViewDemo(
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case 'fluttercandies://image':
      return FFRouteSettings(
        name: 'fluttercandies://image',
        routeName: 'Image',
        description: 'Cached image with border,shape,borderRadius.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
        builder: () => ImageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://imageeditor':
      return FFRouteSettings(
        name: 'fluttercandies://imageeditor',
        routeName: 'ImageEditor',
        description: 'Crop,rotate and flip with image editor.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Complex', 'order': 1},
        builder: () => ImageEditorDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://loadingprogress':
      return FFRouteSettings(
        name: 'fluttercandies://loadingprogress',
        routeName: 'Loading progress',
        description: 'Loading progress for network image.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 2},
        builder: () => LoadingProgress(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: 'fluttercandies://mainpage',
        routeName: 'MainPage',
        arguments: arguments,
        builder: () => MainPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://paintimage':
      return FFRouteSettings(
        name: 'fluttercandies://paintimage',
        routeName: 'Paint image',
        description: 'Paint any thing before or after raw image is painted.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 3},
        builder: () => PaintImageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://photoview':
      return FFRouteSettings(
        name: 'fluttercandies://photoview',
        routeName: 'PhotoView',
        description: 'Complex demo for photo view.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Complex', 'order': 2},
        builder: () => PhotoViewDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://picswiper':
      return FFRouteSettings(
        name: 'fluttercandies://picswiper',
        routeName: 'PicSwiper',
        arguments: arguments,
        showStatusBar: false,
        pageRouteType: PageRouteType.transparent,
        builder: () => PicSwiper(
          key: asT<Key?>(safeArguments['key']),
          index: asT<int?>(safeArguments['index']),
          pics: asT<List<PicSwiperItem>?>(safeArguments['pics']),
          tuChongItem: asT<TuChongItem?>(safeArguments['tuChongItem']),
        ),
      );
    case 'fluttercandies://simpleimageeditor':
      return FFRouteSettings(
        name: 'fluttercandies://simpleimageeditor',
        routeName: 'ImageEditor',
        description: 'Crop with image editor.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 6},
        builder: () => SimpleImageEditor(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://slidepage':
      return FFRouteSettings(
        name: 'fluttercandies://slidepage',
        routeName: 'SlidePage',
        description: 'Simple demo for slide page.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 5},
        builder: () => SlidePageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://slidepageitem':
      return FFRouteSettings(
        name: 'fluttercandies://slidepageitem',
        routeName: 'SlidePageItem',
        description: 'Simple demo for Sliding.',
        arguments: arguments,
        pageRouteType: PageRouteType.transparent,
        builder: () => SlidePage(
          key: asT<Key?>(safeArguments['key']),
          url: asT<String?>(safeArguments['url']),
        ),
      );
    case 'fluttercandies://zoomimage':
      return FFRouteSettings(
        name: 'fluttercandies://zoomimage',
        routeName: 'ImageZoom',
        description: 'Zoom and Pan.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'Simple', 'order': 4},
        builder: () => ZoomImageDemo(key: asT<Key?>(safeArguments['key'])),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
