// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:example/common/data/tu_chong_source.dart' hide asT;
import 'package:example/common/model/pic_swiper_item.dart';
import 'package:flutter/foundation.dart';

import 'pages/main_page.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://LivePhotoDemo',
  'fluttercandies://LivePhotoPicsWiper',
  'fluttercandies://MemoryUsageDemo',
  'fluttercandies://SimplePhotoView',
  'fluttercandies://SimplePicsWiper',
  'fluttercandies://WaterfallFlowDemo',
  'fluttercandies://customimage',
  'fluttercandies://demogrouppage',
  'fluttercandies://extendedImageGesturePageView',
  'fluttercandies://image',
  'fluttercandies://imageeditor',
  'fluttercandies://loadingprogress',
  'fluttercandies://mainpage',
  'fluttercandies://paintimage',
  'fluttercandies://photoview',
  'fluttercandies://picswiper',
  'fluttercandies://simpleimageeditor',
  'fluttercandies://slidepage',
  'fluttercandies://slidepageitem',
  'fluttercandies://zoomimage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'a live photho demo.'
  ///
  /// [name] : 'fluttercandies://LivePhotoDemo'
  ///
  /// [routeName] : 'LivePhoto'
  ///
  /// [description] : 'a live photho demo.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 5}
  static const _FluttercandiesLivePhotoDemo fluttercandiesLivePhotoDemo =
      _FluttercandiesLivePhotoDemo();

  /// 'demo for LivePhoto Pics Wiper.'
  ///
  /// [name] : 'fluttercandies://LivePhotoPicsWiper'
  ///
  /// [routeName] : 'LivePhotoPicsWiper'
  ///
  /// [description] : 'demo for LivePhoto Pics Wiper.'
  ///
  /// [constructors] :
  ///
  /// LivePhotoPicsWiper : [String(required) url, List<String>(required) images, bool stopPlayLivePhotoWhenSlidingPage, bool stopPlayLivePhotoWhenGesture]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesLivePhotoPicsWiper
      fluttercandiesLivePhotoPicsWiper = _FluttercandiesLivePhotoPicsWiper();

  /// 'show how to reduce memory usage.'
  ///
  /// [name] : 'fluttercandies://MemoryUsageDemo'
  ///
  /// [routeName] : 'MemoryUsage'
  ///
  /// [description] : 'show how to reduce memory usage.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 3}
  static const _FluttercandiesMemoryUsageDemo fluttercandiesMemoryUsageDemo =
      _FluttercandiesMemoryUsageDemo();

  /// 'Simple demo for PhotoView.'
  ///
  /// [name] : 'fluttercandies://SimplePhotoView'
  ///
  /// [routeName] : 'SimplePhotoView'
  ///
  /// [description] : 'Simple demo for PhotoView.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 8}
  static const _FluttercandiesSimplePhotoView fluttercandiesSimplePhotoView =
      _FluttercandiesSimplePhotoView();

  /// 'Simple demo for Simple Pics Wiper.'
  ///
  /// [name] : 'fluttercandies://SimplePicsWiper'
  ///
  /// [routeName] : 'SimplePicsWiper'
  ///
  /// [description] : 'Simple demo for Simple Pics Wiper.'
  ///
  /// [constructors] :
  ///
  /// SimplePicsWiper : [String(required) url, List<String>(required) images]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesSimplePicsWiper fluttercandiesSimplePicsWiper =
      _FluttercandiesSimplePicsWiper();

  /// 'WaterfallFlow with ExtendedImage.'
  ///
  /// [name] : 'fluttercandies://WaterfallFlowDemo'
  ///
  /// [routeName] : 'WaterfallFlow'
  ///
  /// [description] : 'WaterfallFlow with ExtendedImage.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 0}
  static const _FluttercandiesWaterfallFlowDemo
      fluttercandiesWaterfallFlowDemo = _FluttercandiesWaterfallFlowDemo();

  /// 'Custom state for loading, failed and completed.'
  ///
  /// [name] : 'fluttercandies://customimage'
  ///
  /// [routeName] : 'Custom load state'
  ///
  /// [description] : 'Custom state for loading, failed and completed.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const _FluttercandiesCustomimage fluttercandiesCustomimage =
      _FluttercandiesCustomimage();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const _FluttercandiesDemogrouppage fluttercandiesDemogrouppage =
      _FluttercandiesDemogrouppage();

  /// 'Simple demo for ExtendedImageGesturePageView.'
  ///
  /// [name] : 'fluttercandies://extendedImageGesturePageView'
  ///
  /// [routeName] : 'ExtendedImageGesturePageView'
  ///
  /// [description] : 'Simple demo for ExtendedImageGesturePageView.'
  ///
  /// [showStatusBar] : false
  ///
  /// [exts] : {'group': 'Simple', 'order': 7}
  static const _FluttercandiesExtendedImageGesturePageView
      fluttercandiesExtendedImageGesturePageView =
      _FluttercandiesExtendedImageGesturePageView();

  /// 'Cached image with border,shape,borderRadius.'
  ///
  /// [name] : 'fluttercandies://image'
  ///
  /// [routeName] : 'Image'
  ///
  /// [description] : 'Cached image with border,shape,borderRadius.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const _FluttercandiesImage fluttercandiesImage =
      _FluttercandiesImage();

  /// 'Crop,rotate and flip with image editor.'
  ///
  /// [name] : 'fluttercandies://imageeditor'
  ///
  /// [routeName] : 'ImageEditor'
  ///
  /// [description] : 'Crop,rotate and flip with image editor.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 1}
  static const _FluttercandiesImageeditor fluttercandiesImageeditor =
      _FluttercandiesImageeditor();

  /// 'Loading progress for network image.'
  ///
  /// [name] : 'fluttercandies://loadingprogress'
  ///
  /// [routeName] : 'Loading progress'
  ///
  /// [description] : 'Loading progress for network image.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const _FluttercandiesLoadingprogress fluttercandiesLoadingprogress =
      _FluttercandiesLoadingprogress();

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const _FluttercandiesMainpage fluttercandiesMainpage =
      _FluttercandiesMainpage();

  /// 'Paint any thing before or after raw image is painted.'
  ///
  /// [name] : 'fluttercandies://paintimage'
  ///
  /// [routeName] : 'Paint image'
  ///
  /// [description] : 'Paint any thing before or after raw image is painted.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 3}
  static const _FluttercandiesPaintimage fluttercandiesPaintimage =
      _FluttercandiesPaintimage();

  /// 'Complex demo for photo view.'
  ///
  /// [name] : 'fluttercandies://photoview'
  ///
  /// [routeName] : 'PhotoView'
  ///
  /// [description] : 'Complex demo for photo view.'
  ///
  /// [exts] : {'group': 'Complex', 'order': 2}
  static const _FluttercandiesPhotoview fluttercandiesPhotoview =
      _FluttercandiesPhotoview();

  /// 'PicSwiper'
  ///
  /// [name] : 'fluttercandies://picswiper'
  ///
  /// [routeName] : 'PicSwiper'
  ///
  /// [constructors] :
  ///
  /// PicSwiper : [int? index, List<PicSwiperItem>? pics, TuChongItem? tuChongItem]
  ///
  /// [showStatusBar] : false
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesPicswiper fluttercandiesPicswiper =
      _FluttercandiesPicswiper();

  /// 'Crop with image editor.'
  ///
  /// [name] : 'fluttercandies://simpleimageeditor'
  ///
  /// [routeName] : 'ImageEditor'
  ///
  /// [description] : 'Crop with image editor.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 6}
  static const _FluttercandiesSimpleimageeditor
      fluttercandiesSimpleimageeditor = _FluttercandiesSimpleimageeditor();

  /// 'Simple demo for slide page.'
  ///
  /// [name] : 'fluttercandies://slidepage'
  ///
  /// [routeName] : 'SlidePage'
  ///
  /// [description] : 'Simple demo for slide page.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 5}
  static const _FluttercandiesSlidepage fluttercandiesSlidepage =
      _FluttercandiesSlidepage();

  /// 'Simple demo for Sliding.'
  ///
  /// [name] : 'fluttercandies://slidepageitem'
  ///
  /// [routeName] : 'SlidePageItem'
  ///
  /// [description] : 'Simple demo for Sliding.'
  ///
  /// [constructors] :
  ///
  /// SlidePage : [String? url]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const _FluttercandiesSlidepageitem fluttercandiesSlidepageitem =
      _FluttercandiesSlidepageitem();

  /// 'Zoom and Pan.'
  ///
  /// [name] : 'fluttercandies://zoomimage'
  ///
  /// [routeName] : 'ImageZoom'
  ///
  /// [description] : 'Zoom and Pan.'
  ///
  /// [exts] : {'group': 'Simple', 'order': 4}
  static const _FluttercandiesZoomimage fluttercandiesZoomimage =
      _FluttercandiesZoomimage();
}

class _FluttercandiesLivePhotoDemo {
  const _FluttercandiesLivePhotoDemo();

  String get name => 'fluttercandies://LivePhotoDemo';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesLivePhotoPicsWiper {
  const _FluttercandiesLivePhotoPicsWiper();

  String get name => 'fluttercandies://LivePhotoPicsWiper';

  Map<String, dynamic> d({
    Key? key,
    required String url,
    required List<String> images,
    bool stopPlayLivePhotoWhenSlidingPage = false,
    bool stopPlayLivePhotoWhenGesture = false,
  }) =>
      <String, dynamic>{
        'key': key,
        'url': url,
        'images': images,
        'stopPlayLivePhotoWhenSlidingPage': stopPlayLivePhotoWhenSlidingPage,
        'stopPlayLivePhotoWhenGesture': stopPlayLivePhotoWhenGesture,
      };

  @override
  String toString() => name;
}

class _FluttercandiesMemoryUsageDemo {
  const _FluttercandiesMemoryUsageDemo();

  String get name => 'fluttercandies://MemoryUsageDemo';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesSimplePhotoView {
  const _FluttercandiesSimplePhotoView();

  String get name => 'fluttercandies://SimplePhotoView';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesSimplePicsWiper {
  const _FluttercandiesSimplePicsWiper();

  String get name => 'fluttercandies://SimplePicsWiper';

  Map<String, dynamic> d({
    Key? key,
    required String url,
    required List<String> images,
  }) =>
      <String, dynamic>{'key': key, 'url': url, 'images': images};

  @override
  String toString() => name;
}

class _FluttercandiesWaterfallFlowDemo {
  const _FluttercandiesWaterfallFlowDemo();

  String get name => 'fluttercandies://WaterfallFlowDemo';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesCustomimage {
  const _FluttercandiesCustomimage();

  String get name => 'fluttercandies://customimage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesDemogrouppage {
  const _FluttercandiesDemogrouppage();

  String get name => 'fluttercandies://demogrouppage';

  Map<String, dynamic> d({
    Key? key,
    required MapEntry<String, List<DemoRouteResult>> keyValue,
  }) =>
      <String, dynamic>{'key': key, 'keyValue': keyValue};

  @override
  String toString() => name;
}

class _FluttercandiesExtendedImageGesturePageView {
  const _FluttercandiesExtendedImageGesturePageView();

  String get name => 'fluttercandies://extendedImageGesturePageView';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesImage {
  const _FluttercandiesImage();

  String get name => 'fluttercandies://image';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesImageeditor {
  const _FluttercandiesImageeditor();

  String get name => 'fluttercandies://imageeditor';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesLoadingprogress {
  const _FluttercandiesLoadingprogress();

  String get name => 'fluttercandies://loadingprogress';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesMainpage {
  const _FluttercandiesMainpage();

  String get name => 'fluttercandies://mainpage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesPaintimage {
  const _FluttercandiesPaintimage();

  String get name => 'fluttercandies://paintimage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesPhotoview {
  const _FluttercandiesPhotoview();

  String get name => 'fluttercandies://photoview';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesPicswiper {
  const _FluttercandiesPicswiper();

  String get name => 'fluttercandies://picswiper';

  Map<String, dynamic> d({
    Key? key,
    int? index,
    List<PicSwiperItem>? pics,
    TuChongItem? tuChongItem,
  }) =>
      <String, dynamic>{
        'key': key,
        'index': index,
        'pics': pics,
        'tuChongItem': tuChongItem,
      };

  @override
  String toString() => name;
}

class _FluttercandiesSimpleimageeditor {
  const _FluttercandiesSimpleimageeditor();

  String get name => 'fluttercandies://simpleimageeditor';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesSlidepage {
  const _FluttercandiesSlidepage();

  String get name => 'fluttercandies://slidepage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}

class _FluttercandiesSlidepageitem {
  const _FluttercandiesSlidepageitem();

  String get name => 'fluttercandies://slidepageitem';

  Map<String, dynamic> d({Key? key, String? url}) => <String, dynamic>{
        'key': key,
        'url': url,
      };

  @override
  String toString() => name;
}

class _FluttercandiesZoomimage {
  const _FluttercandiesZoomimage();

  String get name => 'fluttercandies://zoomimage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{'key': key};

  @override
  String toString() => name;
}
