name: Runnable (stable)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: 'stable'
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: flutter pub get
      - name: Analyse the repo
        run: flutter analyze lib example/lib
      - name: Generate docs
        run: |
          dart pub global activate dartdoc
          dart pub global run dartdoc .

  test_iOS:
    needs: analyze
    name: Test iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: cd example; flutter build ios --no-codesign

  test_android:
    needs: analyze
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: cd example; flutter build apk --debug
